import { Router, json } from 'express';
import { createAppAuth } from '@octokit/auth-app';
import { writeFileSync } from 'fs';
import { randomBytes } from 'node:crypto';
import path from 'path';

export function createSetupRouter(rootDir: string): Router {
  const router = Router();
  router.use(json());

  router.get('/', (_req, res) => {
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.send(WIZARD_HTML);
  });

  router.get('/api/generate-secret', (_req, res) => {
    res.json({ secret: randomBytes(32).toString('hex') });
  });

  router.post('/api/validate-jira', async (req, res) => {
    const { host, email, apiToken } = req.body as { host: string; email: string; apiToken: string };
    try {
      const response = await fetch('https://' + host + '/rest/api/3/myself', {
        headers: {
          'Authorization': 'Basic ' + Buffer.from(email + ':' + apiToken).toString('base64'),
          'Accept': 'application/json',
        },
      });
      if (!response.ok) {
        const text = await response.text();
        return res.json({ ok: false, error: 'Jira returned ' + response.status + ': ' + text.slice(0, 200) });
      }
      const data = await response.json() as { accountId: string; displayName: string };
      return res.json({ ok: true, accountId: data.accountId, displayName: data.displayName });
    } catch (err) {
      return res.json({ ok: false, error: String(err) });
    }
  });

  router.post('/api/validate-github-pat', async (req, res) => {
    const { pat } = req.body as { pat: string };
    try {
      const response = await fetch('https://api.github.com/user', {
        headers: {
          'Authorization': 'token ' + pat,
          'User-Agent': 'JiraBot-Setup',
          'Accept': 'application/vnd.github.v3+json',
        },
      });
      if (!response.ok) {
        return res.json({ ok: false, error: 'GitHub returned ' + response.status + ' — check the token and that the "repo" scope is selected.' });
      }
      const data = await response.json() as { login: string };
      return res.json({ ok: true, login: data.login });
    } catch (err) {
      return res.json({ ok: false, error: String(err) });
    }
  });

  router.post('/api/validate-github-app', async (req, res) => {
    const { appId, privateKey, installationId } = req.body as {
      appId: string; privateKey: string; installationId: string;
    };
    try {
      const auth = createAppAuth({
        appId: Number(appId),
        privateKey: privateKey.replace(/\\n/g, '\n'),
        installationId: Number(installationId),
      });
      await auth({ type: 'installation' });
      return res.json({ ok: true });
    } catch (err) {
      return res.json({ ok: false, error: String(err) });
    }
  });

  router.post('/api/validate-anthropic', async (req, res) => {
    const { apiKey } = req.body as { apiKey: string };
    try {
      const response = await fetch('https://api.anthropic.com/v1/models', {
        headers: { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
      });
      if (!response.ok) {
        return res.json({ ok: false, error: 'Anthropic returned ' + response.status + ' — check the key is valid and not expired.' });
      }
      return res.json({ ok: true });
    } catch (err) {
      return res.json({ ok: false, error: String(err) });
    }
  });

  router.post('/api/save', (req, res) => {
    const { jira, github, anthropicApiKey, boards, slack } = req.body as {
      jira: { host: string; email: string; apiToken: string; accountId: string; webhookSecret: string };
      github: { mode: string; pat?: string; appId?: string; privateKey?: string; installationId?: string };
      anthropicApiKey: string;
      boards: Array<{ jiraProject: string; githubRepo: string; defaultBranch: string; targetStatus: string; escalationStatus: string }>;
      slack?: { botToken: string; signingSecret: string };
    };
    try {
      const lines: string[] = ['# Generated by JiraBot setup wizard', ''];
      lines.push('# Jira');
      lines.push('JIRA_HOST=' + jira.host);
      lines.push('JIRA_AGENT_EMAIL=' + jira.email);
      lines.push('JIRA_API_TOKEN=' + jira.apiToken);
      lines.push('JIRA_AGENT_ACCOUNT_ID=' + jira.accountId);
      lines.push('JIRA_WEBHOOK_SECRET=' + jira.webhookSecret);
      lines.push('');
      lines.push('# GitHub');
      if (github.mode === 'pat') {
        lines.push('GITHUB_PAT=' + (github.pat ?? ''));
      } else {
        lines.push('GITHUB_APP_ID=' + (github.appId ?? ''));
        lines.push('GITHUB_APP_PRIVATE_KEY=' + (github.privateKey ?? '').replace(/\n/g, '\\n'));
        lines.push('GITHUB_APP_INSTALLATION_ID=' + (github.installationId ?? ''));
      }
      lines.push('');
      lines.push('# Anthropic');
      lines.push('ANTHROPIC_API_KEY=' + anthropicApiKey);
      lines.push('');
      lines.push('# Redis (Docker Compose overrides this automatically)');
      lines.push('REDIS_URL=redis://localhost:6379');
      lines.push('');
      lines.push('# Board mapping');
      lines.push('BOARDS_CONFIG=' + JSON.stringify(boards));
      if (slack?.botToken) {
        lines.push('');
        lines.push('# Slack');
        lines.push('SLACK_BOT_TOKEN=' + slack.botToken);
        lines.push('SLACK_SIGNING_SECRET=' + slack.signingSecret);
      }
      lines.push('');
      writeFileSync(path.join(rootDir, '.env'), lines.join('\n'), 'utf8');
      return res.json({ ok: true });
    } catch (err) {
      return res.json({ ok: false, error: String(err) });
    }
  });

  return router;
}

const WIZARD_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>JiraBot Setup</title>
<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html, body { height: 100%; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 14px; color: #1e293b; background: #f1f5f9; }
body { display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; }
code { font-family: 'SF Mono', 'Menlo', 'Monaco', monospace; font-size: 12px; background: #f1f5f9; padding: 1px 5px; border-radius: 4px; }
a { color: #6366f1; text-decoration: none; }
a:hover { text-decoration: underline; }
strong { font-weight: 600; }

.wizard { display: flex; width: 940px; max-width: 100%; min-height: 580px; background: #fff; border-radius: 14px; box-shadow: 0 4px 32px rgba(0,0,0,0.12); overflow: hidden; }

/* ── Sidebar ── */
.sidebar { width: 220px; flex-shrink: 0; background: #0f172a; display: flex; flex-direction: column; }
.brand { color: #fff; font-size: 15px; font-weight: 700; padding: 24px 20px 20px; border-bottom: 1px solid rgba(255,255,255,0.08); display: flex; align-items: center; gap: 10px; }
.brand-icon { width: 30px; height: 30px; background: #6366f1; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 17px; }
.step-list { list-style: none; padding: 12px 0; flex: 1; }
.step-item { display: flex; align-items: center; gap: 10px; padding: 9px 16px; color: #475569; cursor: default; transition: background 0.15s; border-left: 3px solid transparent; }
.step-item.active { color: #e2e8f0; background: rgba(99,102,241,0.15); border-left-color: #6366f1; }
.step-item.done { color: #64748b; }
.step-dot { width: 22px; height: 22px; border-radius: 50%; border: 2px solid #334155; display: flex; align-items: center; justify-content: center; font-size: 10px; font-weight: 700; flex-shrink: 0; transition: all 0.2s; }
.step-item.active .step-dot { border-color: #6366f1; background: #6366f1; color: #fff; }
.step-item.done .step-dot { border-color: #22c55e; background: #22c55e; color: #fff; font-size: 12px; }
.step-label { font-size: 13px; font-weight: 500; }
.sidebar-foot { padding: 16px; border-top: 1px solid rgba(255,255,255,0.08); }
.sidebar-foot p { font-size: 11px; color: #475569; line-height: 1.5; }

/* ── Content ── */
.content { flex: 1; display: flex; flex-direction: column; min-width: 0; }
.progress-bar { height: 3px; background: #e2e8f0; flex-shrink: 0; }
.progress-fill { height: 100%; background: #6366f1; transition: width 0.35s ease; }
.panel { flex: 1; padding: 32px 36px 24px; display: none; flex-direction: column; gap: 20px; overflow-y: auto; }
.panel.active { display: flex; }
.panel-hd h2 { font-size: 19px; font-weight: 700; color: #0f172a; margin-bottom: 3px; }
.panel-hd p { font-size: 13px; color: #64748b; line-height: 1.5; }

/* ── Fields ── */
.field { display: flex; flex-direction: column; gap: 5px; }
.field label { font-size: 12px; font-weight: 700; color: #374151; text-transform: uppercase; letter-spacing: 0.04em; }
.field input, .field textarea {
  border: 1.5px solid #e2e8f0; border-radius: 8px; padding: 8px 11px;
  font-size: 13px; font-family: inherit; outline: none; transition: border-color 0.15s, box-shadow 0.15s;
  background: #fff; color: #1e293b; width: 100%;
}
.field input:focus, .field textarea:focus { border-color: #6366f1; box-shadow: 0 0 0 3px rgba(99,102,241,0.12); }
.field textarea { resize: vertical; min-height: 90px; font-family: 'SF Mono', 'Menlo', 'Monaco', monospace; font-size: 11.5px; line-height: 1.5; }
.field-hint { font-size: 12px; color: #94a3b8; line-height: 1.6; }
.field-row { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
.field-row3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 14px; }

/* ── Buttons ── */
.btn { display: inline-flex; align-items: center; gap: 6px; padding: 8px 16px; border-radius: 8px; font-size: 13px; font-weight: 600; cursor: pointer; border: none; transition: all 0.15s; font-family: inherit; line-height: 1; }
.btn:disabled { opacity: 0.55; cursor: not-allowed; }
.btn-primary { background: #6366f1; color: #fff; }
.btn-primary:not(:disabled):hover { background: #4f46e5; }
.btn-outline { background: #fff; color: #6366f1; border: 1.5px solid #c7d2fe; }
.btn-outline:not(:disabled):hover { background: #eef2ff; }
.btn-ghost { background: #fff; color: #64748b; border: 1.5px solid #e2e8f0; }
.btn-ghost:not(:disabled):hover { background: #f8fafc; }
.btn-success { background: #f0fdf4; color: #15803d; border: 1.5px solid #bbf7d0; }
.btn-danger { background: #fff; color: #ef4444; border: 1.5px solid #fecaca; font-size: 12px; padding: 5px 10px; }
.btn-danger:not(:disabled):hover { background: #fef2f2; }
.btn-sm { padding: 6px 12px; font-size: 12px; }
.btn-add { background: #f8fafc; color: #475569; border: 1.5px dashed #cbd5e1; font-size: 12px; padding: 7px 14px; border-radius: 8px; cursor: pointer; font-family: inherit; font-weight: 500; transition: all 0.15s; }
.btn-add:hover { border-color: #6366f1; color: #6366f1; background: #eef2ff; }

/* ── Status ── */
.msg { display: flex; align-items: flex-start; gap: 9px; padding: 11px 13px; border-radius: 8px; font-size: 13px; line-height: 1.5; }
.msg-success { background: #f0fdf4; border: 1px solid #bbf7d0; color: #15803d; }
.msg-error { background: #fef2f2; border: 1px solid #fecaca; color: #991b1b; }
.msg-info { background: #eff6ff; border: 1px solid #bfdbfe; color: #1e40af; }
.msg-icon { font-size: 14px; flex-shrink: 0; margin-top: 1px; }
.hidden { display: none !important; }

/* ── Radio cards (GitHub auth) ── */
.radio-group { display: flex; gap: 10px; }
.radio-card { flex: 1; border: 2px solid #e2e8f0; border-radius: 10px; padding: 14px; cursor: pointer; transition: all 0.15s; user-select: none; }
.radio-card:hover { border-color: #c7d2fe; background: #fafafe; }
.radio-card.sel { border-color: #6366f1; background: #eef2ff; }
.radio-card input[type=radio] { display: none; }
.radio-card-title { font-size: 13px; font-weight: 700; color: #1e293b; margin-bottom: 3px; }
.radio-card-desc { font-size: 12px; color: #64748b; }
.radio-badge { display: inline-block; font-size: 10px; font-weight: 700; padding: 1px 6px; border-radius: 4px; background: #dcfce7; color: #15803d; margin-left: 6px; vertical-align: middle; }

/* ── Board cards ── */
.board-card { border: 1.5px solid #e2e8f0; border-radius: 10px; padding: 18px; position: relative; }
.board-card + .board-card { margin-top: 10px; }
.board-hd { display: flex; align-items: center; justify-content: space-between; margin-bottom: 14px; }
.board-label { font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }

/* ── Slack toggle ── */
.toggle-row { display: flex; align-items: center; gap: 12px; }
.toggle { position: relative; width: 38px; height: 21px; flex-shrink: 0; }
.toggle input { opacity: 0; width: 0; height: 0; position: absolute; }
.toggle-track { position: absolute; inset: 0; background: #cbd5e1; border-radius: 999px; cursor: pointer; transition: background 0.2s; }
.toggle input:checked + .toggle-track { background: #6366f1; }
.toggle-thumb { position: absolute; height: 15px; width: 15px; left: 3px; top: 3px; background: #fff; border-radius: 50%; transition: transform 0.2s; box-shadow: 0 1px 4px rgba(0,0,0,0.2); pointer-events: none; }
.toggle input:checked ~ .toggle-thumb { transform: translateX(17px); }
.toggle-lbl { font-size: 13px; font-weight: 600; color: #374151; }

/* ── Navigation bar ── */
.nav { border-top: 1px solid #f1f5f9; padding: 16px 36px; display: flex; align-items: center; justify-content: space-between; flex-shrink: 0; }
.nav-right { display: flex; gap: 8px; align-items: center; }
.step-hint { font-size: 12px; color: #94a3b8; }

/* ── Review / Done ── */
.review-grid { display: grid; gap: 8px; }
.review-row { display: flex; align-items: center; gap: 10px; padding: 11px 14px; background: #f8fafc; border-radius: 9px; font-size: 13px; }
.review-check { font-size: 15px; flex-shrink: 0; }
.review-key { width: 90px; color: #64748b; font-weight: 500; flex-shrink: 0; }
.review-val { color: #1e293b; font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.webhook-block { background: #0f172a; border-radius: 9px; padding: 16px 18px; font-size: 12px; line-height: 2; font-family: 'SF Mono', 'Menlo', 'Monaco', monospace; }
.wk { color: #7dd3fc; }
.wv { color: #86efac; }
.next-steps-hd { font-size: 12px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px; }
.cmd { display: inline-block; background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 6px; padding: 2px 8px; font-family: 'SF Mono', 'Menlo', monospace; font-size: 12px; color: #4f46e5; }
.step-list-item { font-size: 13px; color: #475569; line-height: 1.9; }

@media (max-width: 680px) {
  .sidebar { display: none; }
  .panel { padding: 24px 20px 16px; }
  .nav { padding: 14px 20px; }
  .field-row, .field-row3 { grid-template-columns: 1fr; }
}
</style>
</head>
<body>
<div class="wizard">
  <!-- Sidebar -->
  <aside class="sidebar">
    <div class="brand"><div class="brand-icon">&#9889;</div>JiraBot</div>
    <ul class="step-list" id="step-list">
      <li class="step-item" data-step="0"><div class="step-dot" id="dot-0">1</div><span class="step-label">Jira Cloud</span></li>
      <li class="step-item" data-step="1"><div class="step-dot" id="dot-1">2</div><span class="step-label">GitHub</span></li>
      <li class="step-item" data-step="2"><div class="step-dot" id="dot-2">3</div><span class="step-label">Anthropic</span></li>
      <li class="step-item" data-step="3"><div class="step-dot" id="dot-3">4</div><span class="step-label">Project Boards</span></li>
      <li class="step-item" data-step="4"><div class="step-dot" id="dot-4">5</div><span class="step-label">Slack</span></li>
      <li class="step-item" data-step="5"><div class="step-dot" id="dot-5">6</div><span class="step-label">Save &amp; finish</span></li>
    </ul>
    <div class="sidebar-foot"><p>All credentials stay on your machine — this wizard writes directly to .env.</p></div>
  </aside>

  <!-- Main content -->
  <div class="content">
    <div class="progress-bar"><div class="progress-fill" id="prog"></div></div>

    <!-- ─── Step 0: Jira ─── -->
    <div class="panel" id="panel-0">
      <div class="panel-hd">
        <h2>Jira Cloud</h2>
        <p>Connect JiraBot to your Jira workspace. Use the credentials of a dedicated agent user — not your personal account.</p>
      </div>
      <div class="field">
        <label for="jira-host">Host</label>
        <input type="text" id="jira-host" placeholder="yourorg.atlassian.net" autocomplete="off">
        <span class="field-hint">Your Jira Cloud domain — omit <code>https://</code>. Found in your browser's address bar.</span>
      </div>
      <div class="field-row">
        <div class="field">
          <label for="jira-email">Agent email</label>
          <input type="email" id="jira-email" placeholder="jirabot@yourcompany.com">
          <span class="field-hint">The email of the Jira user JiraBot acts as. We recommend a dedicated service account.</span>
        </div>
        <div class="field">
          <label for="jira-token">API token</label>
          <input type="password" id="jira-token" placeholder="ATATT3xFf&#8230;">
          <span class="field-hint">
            Create at <a href="https://id.atlassian.com/manage-profile/security/api-tokens" target="_blank">id.atlassian.com &#8594; Security &#8594; API tokens</a>. Use the agent account, not yours.
          </span>
        </div>
      </div>
      <div>
        <button class="btn btn-primary" id="btn-verify-jira">Verify connection</button>
      </div>
      <div id="msg-jira" class="hidden"></div>
    </div>

    <!-- ─── Step 1: GitHub ─── -->
    <div class="panel" id="panel-1">
      <div class="panel-hd">
        <h2>GitHub</h2>
        <p>JiraBot needs permission to create branches and open pull requests on your behalf.</p>
      </div>
      <div class="radio-group">
        <label class="radio-card sel" id="card-pat" onclick="setGhMode('pat')">
          <input type="radio" name="gh-mode" value="pat" checked>
          <div class="radio-card-title">Personal Access Token <span class="radio-badge">Easier</span></div>
          <div class="radio-card-desc">One token, two minutes. Best for local&nbsp;use.</div>
        </label>
        <label class="radio-card" id="card-app" onclick="setGhMode('app')">
          <input type="radio" name="gh-mode" value="app">
          <div class="radio-card-title">GitHub App</div>
          <div class="radio-card-desc">Scoped permissions. Best for production or teams.</div>
        </label>
      </div>

      <!-- PAT fields -->
      <div id="gh-pat-fields" style="display:flex;flex-direction:column;gap:16px">
        <div class="field">
          <label for="gh-pat">Personal access token</label>
          <input type="password" id="gh-pat" placeholder="ghp_&#8230;" autocomplete="off">
          <span class="field-hint">
            Generate at <a href="https://github.com/settings/tokens/new" target="_blank">github.com &#8594; Settings &#8594; Developer settings &#8594; Personal access tokens &#8594; Tokens (classic) &#8594; Generate new token (classic)</a>.
            Enable the <strong>repo</strong> scope (full control of private repositories).
          </span>
        </div>
      </div>

      <!-- App fields -->
      <div id="gh-app-fields" style="display:none;flex-direction:column;gap:16px">
        <div class="field">
          <label for="gh-app-id">App ID</label>
          <input type="text" id="gh-app-id" placeholder="123456" autocomplete="off">
          <span class="field-hint">
            Open <a href="https://github.com/settings/apps" target="_blank">github.com &#8594; Settings &#8594; Developer settings &#8594; GitHub Apps</a> &#8594; click your app &#8594; the <strong>App ID</strong> is shown at the top of the <em>About this App</em> section.
          </span>
        </div>
        <div class="field">
          <label for="gh-pem">Private key (PEM)</label>
          <textarea id="gh-pem" placeholder="-----BEGIN RSA PRIVATE KEY-----&#10;MIIEowIBAAK&#8230;&#10;-----END RSA PRIVATE KEY-----"></textarea>
          <span class="field-hint">
            On the same GitHub App page, scroll to <strong>Private keys</strong> &#8594; <strong>Generate a private key</strong>. A .pem file downloads — open it in any text editor, select all, and paste here.
          </span>
        </div>
        <div class="field">
          <label for="gh-install-id">Installation ID</label>
          <input type="text" id="gh-install-id" placeholder="45678901" autocomplete="off">
          <span class="field-hint">
            After installing the app on your org or repo, go to <a href="https://github.com/settings/installations" target="_blank">github.com &#8594; Settings &#8594; Applications &#8594; Installed GitHub Apps</a> &#8594; click <strong>Configure</strong> next to your app. The URL ends with <code>/installations/<strong>45678901</strong></code> — that number is the Installation ID.
          </span>
        </div>
      </div>

      <div>
        <button class="btn btn-primary" id="btn-verify-gh">Verify connection</button>
      </div>
      <div id="msg-gh" class="hidden"></div>
    </div>

    <!-- ─── Step 2: Anthropic ─── -->
    <div class="panel" id="panel-2">
      <div class="panel-hd">
        <h2>Anthropic</h2>
        <p>JiraBot uses Claude to read tickets, decide if it has enough information, write code, and know when to escalate.</p>
      </div>
      <div class="field">
        <label for="anth-key">API key</label>
        <input type="password" id="anth-key" placeholder="sk-ant-api03-&#8230;" autocomplete="off">
        <span class="field-hint">
          Create a key at <a href="https://console.anthropic.com/settings/api-keys" target="_blank">console.anthropic.com &#8594; Settings &#8594; API keys &#8594; Create Key</a>.
          JiraBot uses <code>claude-sonnet-4-6</code> for reasoning and <code>claude-haiku-4-5</code> for quick tasks.
        </span>
      </div>
      <div>
        <button class="btn btn-primary" id="btn-verify-anth">Verify key</button>
      </div>
      <div id="msg-anth" class="hidden"></div>
    </div>

    <!-- ─── Step 3: Project Boards ─── -->
    <div class="panel" id="panel-3">
      <div class="panel-hd">
        <h2>Project Boards</h2>
        <p>Tell JiraBot which Jira project maps to which GitHub repository. Add one row per project.</p>
      </div>
      <div id="boards-wrap"></div>
      <div>
        <button class="btn-add" id="btn-add-board">+ Add another board</button>
      </div>
      <div id="msg-boards" class="hidden"></div>
    </div>

    <!-- ─── Step 4: Slack ─── -->
    <div class="panel" id="panel-4">
      <div class="panel-hd">
        <h2>Slack <span style="font-size:13px;font-weight:400;color:#94a3b8">(optional)</span></h2>
        <p>Enable to post PR notifications to Slack channels and let developers ask questions via DM.</p>
      </div>
      <div class="toggle-row">
        <label class="toggle">
          <input type="checkbox" id="slack-toggle" onchange="onSlackToggle()">
          <div class="toggle-track"></div>
          <div class="toggle-thumb"></div>
        </label>
        <span class="toggle-lbl">Enable Slack</span>
      </div>
      <div id="slack-fields" style="display:none;flex-direction:column;gap:16px">
        <div class="field">
          <label for="slack-token">Bot token</label>
          <input type="password" id="slack-token" placeholder="xoxb-&#8230;" autocomplete="off">
          <span class="field-hint">
            <strong>Step 1:</strong> Create a Slack app at <a href="https://api.slack.com/apps" target="_blank">api.slack.com/apps &#8594; Create New App &#8594; From scratch</a>.<br>
            <strong>Step 2:</strong> Go to <strong>OAuth &amp; Permissions &#8594; Scopes &#8594; Bot Token Scopes</strong> and add: <code>chat:write</code>, <code>im:history</code>, <code>app_mentions:read</code>.<br>
            <strong>Step 3:</strong> Click <strong>Install to Workspace</strong>. Copy the <strong>Bot User OAuth Token</strong> (<code>xoxb-&#8230;</code>).
          </span>
        </div>
        <div class="field">
          <label for="slack-secret">Signing secret</label>
          <input type="password" id="slack-secret" placeholder="a1b2c3&#8230;" autocomplete="off">
          <span class="field-hint">
            In the same Slack app settings: <strong>Basic Information &#8594; App Credentials &#8594; Signing Secret</strong>.
            Used to verify that webhook events come from Slack.
          </span>
        </div>
      </div>
      <div class="msg msg-info" style="margin-top:4px">
        <span class="msg-icon">&#8505;</span>
        <span>You can skip this now and add Slack later by editing <code>.env</code> and restarting the agent.</span>
      </div>
    </div>

    <!-- ─── Step 5: Save ─── -->
    <div class="panel" id="panel-5">
      <div class="panel-hd">
        <h2>Save &amp; finish</h2>
        <p>Review your configuration, then save it to <code>.env</code> in the project root.</p>
      </div>
      <div class="review-grid" id="review-rows"></div>
      <div style="display:flex;gap:10px;flex-wrap:wrap">
        <button class="btn btn-primary" id="btn-save" style="min-width:140px">Save .env file</button>
      </div>
      <div id="msg-save" class="hidden"></div>
      <div id="next-steps" class="hidden" style="display:flex;flex-direction:column;gap:14px">
        <div>
          <div class="next-steps-hd">Start the agent</div>
          <div class="step-list-item">Run <span class="cmd">./scripts/start-local.sh</span> — it starts Docker Compose, opens an ngrok tunnel, and registers the Jira webhook automatically.</div>
        </div>
        <div>
          <div class="next-steps-hd">Manual webhook setup (if needed)</div>
          <div id="webhook-block" class="webhook-block"></div>
        </div>
        <div>
          <div class="next-steps-hd">Test it</div>
          <div class="step-list-item">Assign a Jira ticket in your project to the agent user. JiraBot will pick it up within seconds.</div>
        </div>
      </div>
    </div>

    <!-- Navigation bar -->
    <div class="nav">
      <button class="btn btn-ghost" id="btn-back">&#8592; Back</button>
      <div class="nav-right">
        <span class="step-hint" id="step-hint"></span>
        <button class="btn btn-primary" id="btn-next" style="min-width:90px">Next &#8594;</button>
      </div>
    </div>
  </div>
</div>

<script>
// ─── State ───────────────────────────────────────────────────
var step = 0;
var verified = [false, false, false, false, true, false];
var ghMode = 'pat';
var savedState = {
  jiraDisplayName: '',
  jiraAccountId: '',
  jiraWebhookSecret: '',
  githubLogin: '',
};
var boardCount = 0;

// ─── Helpers ─────────────────────────────────────────────────
function g(id) { return document.getElementById(id); }

function showMsg(id, type, html) {
  var el = g(id);
  el.className = 'msg msg-' + type;
  var icon = type === 'success' ? '&#10003;' : type === 'error' ? '&#10005;' : '&#8505;';
  el.innerHTML = '<span class="msg-icon">' + icon + '</span><div>' + html + '</div>';
  el.classList.remove('hidden');
}
function hideMsg(id) { g(id).classList.add('hidden'); }

function setBtn(id, text, disabled) {
  g(id).textContent = text;
  g(id).disabled = disabled;
}

// ─── Navigation ──────────────────────────────────────────────
function goTo(s) {
  step = s;
  document.querySelectorAll('.panel').forEach(function(p) { p.classList.remove('active'); });
  g('panel-' + s).classList.add('active');
  // Sidebar
  document.querySelectorAll('.step-item').forEach(function(item, i) {
    item.classList.remove('active', 'done');
    var dot = g('dot-' + i);
    if (i === s) {
      item.classList.add('active');
      dot.textContent = String(i + 1);
    } else if (verified[i]) {
      item.classList.add('done');
      dot.innerHTML = '&#10003;';
    } else {
      dot.textContent = String(i + 1);
    }
  });
  // Progress bar
  g('prog').style.width = (s / 5 * 100) + '%';
  // Back/Next visibility
  g('btn-back').style.visibility = s === 0 ? 'hidden' : 'visible';
  g('btn-next').style.display = s === 5 ? 'none' : '';
  // Step hint
  var hints = ['', '', '', '', 'This step is optional', ''];
  g('step-hint').textContent = hints[s] || '';
  // Build review when landing on last step
  if (s === 5) buildReview();
}

g('btn-next').addEventListener('click', function() {
  if (step === 0 && !verified[0]) { showMsg('msg-jira', 'error', 'Verify your Jira connection before continuing.'); return; }
  if (step === 1 && !verified[1]) { showMsg('msg-gh', 'error', 'Verify your GitHub connection before continuing.'); return; }
  if (step === 2 && !verified[2]) { showMsg('msg-anth', 'error', 'Verify your Anthropic key before continuing.'); return; }
  if (step === 3) {
    var bs = getBoards();
    if (bs.length === 0) { showMsg('msg-boards', 'error', 'Add at least one board with a Jira project key and GitHub repo.'); return; }
    hideMsg('msg-boards');
    verified[3] = true;
  }
  if (step < 5) goTo(step + 1);
});
g('btn-back').addEventListener('click', function() { if (step > 0) goTo(step - 1); });

// ─── GitHub mode toggle ───────────────────────────────────────
function setGhMode(mode) {
  ghMode = mode;
  g('card-pat').classList.toggle('sel', mode === 'pat');
  g('card-app').classList.toggle('sel', mode === 'app');
  g('gh-pat-fields').style.display = mode === 'pat' ? 'flex' : 'none';
  g('gh-app-fields').style.display = mode === 'app' ? 'flex' : 'none';
  verified[1] = false;
  hideMsg('msg-gh');
}

// ─── Slack toggle ─────────────────────────────────────────────
function onSlackToggle() {
  g('slack-fields').style.display = g('slack-toggle').checked ? 'flex' : 'none';
}

// ─── Jira verify ─────────────────────────────────────────────
g('btn-verify-jira').addEventListener('click', function() {
  var host = g('jira-host').value.trim().replace(/^https?:\/\//, '');
  var email = g('jira-email').value.trim();
  var token = g('jira-token').value.trim();
  if (!host || !email || !token) { showMsg('msg-jira', 'error', 'Fill in all three fields before verifying.'); return; }
  setBtn('btn-verify-jira', 'Verifying&#8230;', true);
  fetch('/setup/api/validate-jira', {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ host: host, email: email, apiToken: token }),
  }).then(function(r) { return r.json(); }).then(function(d) {
    setBtn('btn-verify-jira', 'Verify connection', false);
    if (d.ok) {
      savedState.jiraDisplayName = d.displayName;
      savedState.jiraAccountId = d.accountId;
      verified[0] = true;
      showMsg('msg-jira', 'success', 'Connected as <strong>' + d.displayName + '</strong> &mdash; account ID: <code>' + d.accountId + '</code>');
      // Fetch webhook secret
      fetch('/setup/api/generate-secret').then(function(r2) { return r2.json(); }).then(function(s) { savedState.jiraWebhookSecret = s.secret; });
    } else {
      verified[0] = false;
      showMsg('msg-jira', 'error', d.error || 'Connection failed.');
    }
    goTo(step); // refresh sidebar
  }).catch(function(e) { setBtn('btn-verify-jira', 'Verify connection', false); showMsg('msg-jira', 'error', String(e)); });
});

// ─── GitHub verify ────────────────────────────────────────────
g('btn-verify-gh').addEventListener('click', function() {
  setBtn('btn-verify-gh', 'Verifying&#8230;', true);
  var endpoint, payload;
  if (ghMode === 'pat') {
    var pat = g('gh-pat').value.trim();
    if (!pat) { setBtn('btn-verify-gh', 'Verify connection', false); showMsg('msg-gh', 'error', 'Enter a token first.'); return; }
    endpoint = '/setup/api/validate-github-pat';
    payload = { pat: pat };
  } else {
    var appId = g('gh-app-id').value.trim();
    var pem = g('gh-pem').value.trim();
    var instId = g('gh-install-id').value.trim();
    if (!appId || !pem || !instId) { setBtn('btn-verify-gh', 'Verify connection', false); showMsg('msg-gh', 'error', 'Fill in App ID, private key, and Installation ID.'); return; }
    endpoint = '/setup/api/validate-github-app';
    payload = { appId: appId, privateKey: pem, installationId: instId };
  }
  fetch(endpoint, {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  }).then(function(r) { return r.json(); }).then(function(d) {
    setBtn('btn-verify-gh', 'Verify connection', false);
    if (d.ok) {
      savedState.githubLogin = d.login || '';
      verified[1] = true;
      var who = ghMode === 'pat' ? ('Connected as <strong>' + d.login + '</strong>') : 'GitHub App authenticated successfully.';
      showMsg('msg-gh', 'success', who);
    } else {
      verified[1] = false;
      showMsg('msg-gh', 'error', d.error || 'Authentication failed.');
    }
    goTo(step);
  }).catch(function(e) { setBtn('btn-verify-gh', 'Verify connection', false); showMsg('msg-gh', 'error', String(e)); });
});

// ─── Anthropic verify ────────────────────────────────────────
g('btn-verify-anth').addEventListener('click', function() {
  var key = g('anth-key').value.trim();
  if (!key) { showMsg('msg-anth', 'error', 'Enter an API key first.'); return; }
  setBtn('btn-verify-anth', 'Verifying&#8230;', true);
  fetch('/setup/api/validate-anthropic', {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ apiKey: key }),
  }).then(function(r) { return r.json(); }).then(function(d) {
    setBtn('btn-verify-anth', 'Verify key', false);
    if (d.ok) {
      verified[2] = true;
      showMsg('msg-anth', 'success', 'API key is valid.');
    } else {
      verified[2] = false;
      showMsg('msg-anth', 'error', d.error || 'Invalid key.');
    }
    goTo(step);
  }).catch(function(e) { setBtn('btn-verify-anth', 'Verify key', false); showMsg('msg-anth', 'error', String(e)); });
});

// ─── Board cards ─────────────────────────────────────────────
function mkBoard(i) {
  var isFirst = i === 0;
  var d = document.createElement('div');
  d.className = 'board-card';
  d.id = 'bc-' + i;
  d.innerHTML =
    '<div class="board-hd"><span class="board-label">Board ' + (i + 1) + '</span>' +
    (isFirst ? '' : '<button class="btn btn-danger btn-sm" onclick="rmBoard(this)">Remove</button>') + '</div>' +
    '<div class="field-row">' +
      '<div class="field">' +
        '<label>Jira project key</label>' +
        '<input type="text" name="proj" placeholder="PROJ" style="text-transform:uppercase" autocomplete="off">' +
        '<span class="field-hint">The prefix before issue numbers. For <strong>PROJ-123</strong>, the key is <strong>PROJ</strong>. Find it at <strong>Project settings &#8594; Details &#8594; Key</strong>.</span>' +
      '</div>' +
      '<div class="field">' +
        '<label>GitHub repo</label>' +
        '<input type="text" name="repo" placeholder="org/repo" autocomplete="off">' +
        '<span class="field-hint">The repo where the bot pushes branches and opens PRs. Format: <code>owner/repo</code>.</span>' +
      '</div>' +
    '</div>' +
    '<div class="field-row3" style="margin-top:12px">' +
      '<div class="field">' +
        '<label>Default branch</label>' +
        '<input type="text" name="branch" placeholder="main" value="main">' +
        '<span class="field-hint">Base branch for pull requests.</span>' +
      '</div>' +
      '<div class="field">' +
        '<label>Target status</label>' +
        '<input type="text" name="target" placeholder="Ready for Review" value="Ready for Review">' +
        '<span class="field-hint">Jira status to set when a PR is opened. Must match exactly &mdash; check <strong>Project settings &#8594; Statuses</strong>.</span>' +
      '</div>' +
      '<div class="field">' +
        '<label>Escalation status</label>' +
        '<input type="text" name="escalation" placeholder="Needs Clarity" value="Needs Clarity">' +
        '<span class="field-hint">Jira status when the bot can\'t complete a ticket and a human needs to step in.</span>' +
      '</div>' +
    '</div>';
  return d;
}
function rmBoard(btn) { btn.closest('.board-card').remove(); }
g('btn-add-board').addEventListener('click', function() {
  g('boards-wrap').appendChild(mkBoard(boardCount++));
});
function getBoards() {
  var out = [];
  document.querySelectorAll('.board-card').forEach(function(card) {
    var proj = card.querySelector('[name=proj]').value.trim().toUpperCase();
    var repo = card.querySelector('[name=repo]').value.trim();
    if (!proj || !repo) return;
    out.push({
      jiraProject: proj,
      githubRepo: repo,
      defaultBranch: card.querySelector('[name=branch]').value.trim() || 'main',
      targetStatus: card.querySelector('[name=target]').value.trim() || 'Ready for Review',
      escalationStatus: card.querySelector('[name=escalation]').value.trim() || 'Needs Clarity',
    });
  });
  return out;
}

// ─── Review ──────────────────────────────────────────────────
function buildReview() {
  var host = g('jira-host').value.trim().replace(/^https?:\/\//, '');
  var boards = getBoards();
  var slackOn = g('slack-toggle').checked;
  var ghDesc = ghMode === 'pat'
    ? 'PAT (' + (savedState.githubLogin || 'authenticated') + ')'
    : 'App ID ' + (g('gh-app-id').value.trim() || '?');
  var boardDesc = boards.length ? boards.map(function(b) { return b.jiraProject + ' &#8594; ' + b.githubRepo; }).join(', ') : 'None configured';
  var rows = [
    ['&#10003;', 'Jira', host + ' &mdash; ' + (savedState.jiraDisplayName || 'connected')],
    ['&#10003;', 'GitHub', ghDesc],
    ['&#10003;', 'Anthropic', 'Key configured'],
    [boards.length ? '&#10003;' : '&#9888;', 'Boards', boardDesc],
    [slackOn ? '&#10003;' : '&mdash;', 'Slack', slackOn ? 'Enabled' : 'Disabled'],
  ];
  g('review-rows').innerHTML = rows.map(function(r) {
    return '<div class="review-row"><span class="review-check">' + r[0] + '</span><span class="review-key">' + r[1] + '</span><span class="review-val">' + r[2] + '</span></div>';
  }).join('');
  // Webhook block
  var secret = savedState.jiraWebhookSecret || '(generated on save)';
  g('webhook-block').innerHTML =
    '<div><span class="wk">URL:    </span><span class="wv">https://&lt;ngrok-url&gt;/webhook/jira</span></div>' +
    '<div><span class="wk">Secret: </span><span class="wv">' + secret + '</span></div>' +
    '<div><span class="wk">Events: </span><span class="wv">Issue &#8594; updated</span></div>';
}

// ─── Save .env ───────────────────────────────────────────────
g('btn-save').addEventListener('click', function() {
  var boards = getBoards();
  if (!boards.length) { showMsg('msg-save', 'error', 'Add at least one board mapping before saving.'); return; }
  var slackOn = g('slack-toggle').checked;
  var payload = {
    jira: {
      host: g('jira-host').value.trim().replace(/^https?:\/\//, ''),
      email: g('jira-email').value.trim(),
      apiToken: g('jira-token').value.trim(),
      accountId: savedState.jiraAccountId,
      webhookSecret: savedState.jiraWebhookSecret,
    },
    github: ghMode === 'pat'
      ? { mode: 'pat', pat: g('gh-pat').value.trim() }
      : { mode: 'app', appId: g('gh-app-id').value.trim(), privateKey: g('gh-pem').value.trim(), installationId: g('gh-install-id').value.trim() },
    anthropicApiKey: g('anth-key').value.trim(),
    boards: boards,
    slack: slackOn ? { botToken: g('slack-token').value.trim(), signingSecret: g('slack-secret').value.trim() } : undefined,
  };
  setBtn('btn-save', 'Saving&#8230;', true);
  fetch('/setup/api/save', {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  }).then(function(r) { return r.json(); }).then(function(d) {
    if (d.ok) {
      g('btn-save').textContent = 'Saved';
      g('btn-save').className = 'btn btn-success';
      showMsg('msg-save', 'success', '.env saved. Run <span class="cmd">docker-compose restart agent</span> (or <span class="cmd">./scripts/start-local.sh</span>) to apply.');
      var ns = g('next-steps');
      ns.classList.remove('hidden');
      ns.style.display = 'flex';
    } else {
      setBtn('btn-save', 'Save .env file', false);
      showMsg('msg-save', 'error', d.error || 'Save failed.');
    }
  }).catch(function(e) { setBtn('btn-save', 'Save .env file', false); showMsg('msg-save', 'error', String(e)); });
});

// ─── Init ────────────────────────────────────────────────────
g('boards-wrap').appendChild(mkBoard(boardCount++));
goTo(0);
</script>
</body>
</html>`;
