#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

echo -e "${CYAN}JiraBot Setup${NC}"
echo ""

# ── Check prerequisites ──
for cmd in docker curl openssl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo -e "${RED}Required command not found: $cmd${NC}"
    exit 1
  fi
done

if [ -f .env ]; then
  read -rp "$(echo -e "${YELLOW}.env already exists. Overwrite? [y/N]: ${NC}")" OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy] ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# ── Jira ──
echo -e "${YELLOW}Jira Cloud${NC}"
read -rp "  Host (e.g. yourorg.atlassian.net): " JIRA_HOST
read -rp "  Agent email: " JIRA_AGENT_EMAIL
read -rsp "  API token: " JIRA_API_TOKEN
echo ""

# Auto-fetch account ID
echo -n "  Fetching account ID... "
JIRA_ACCOUNT_ID=""
JIRA_ACCOUNT_ID=$(curl -sf -u "$JIRA_AGENT_EMAIL:$JIRA_API_TOKEN" \
  "https://$JIRA_HOST/rest/api/3/myself" 2>/dev/null \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['accountId'])" 2>/dev/null) || true

if [ -z "$JIRA_ACCOUNT_ID" ]; then
  echo -e "${YELLOW}could not auto-detect${NC}"
  read -rp "  Enter account ID manually: " JIRA_ACCOUNT_ID
else
  echo -e "${GREEN}$JIRA_ACCOUNT_ID${NC}"
fi

# Generate webhook secret
JIRA_WEBHOOK_SECRET=$(openssl rand -hex 32)
echo -e "  Webhook secret: ${GREEN}auto-generated${NC}"

# ── GitHub ──
echo ""
echo -e "${YELLOW}GitHub${NC}"
echo "  1) Personal Access Token (simpler)"
echo "  2) GitHub App"
read -rp "  Auth method [1]: " GH_CHOICE
GH_CHOICE=${GH_CHOICE:-1}

GITHUB_PAT=""
GITHUB_APP_ID=""
GITHUB_APP_PRIVATE_KEY=""
GITHUB_APP_INSTALLATION_ID=""

if [ "$GH_CHOICE" = "2" ]; then
  read -rp "  App ID: " GITHUB_APP_ID
  read -rp "  Private key .pem path: " GH_KEY_PATH
  if [ ! -f "$GH_KEY_PATH" ]; then
    echo -e "${RED}  File not found: $GH_KEY_PATH${NC}"
    exit 1
  fi
  # Convert PEM to single line with \n escapes for .env compatibility
  GITHUB_APP_PRIVATE_KEY=$(awk '{printf "%s\\n",$0}' "$GH_KEY_PATH")
  read -rp "  Installation ID: " GITHUB_APP_INSTALLATION_ID
else
  echo ""
  echo "  Create a token at: https://github.com/settings/tokens/new"
  echo "  Select the 'repo' scope."
  read -rsp "  Token (ghp_...): " GITHUB_PAT
  echo ""
fi

# ── Anthropic ──
echo ""
echo -e "${YELLOW}Anthropic${NC}"
read -rsp "  API key (sk-ant-...): " ANTHROPIC_API_KEY
echo ""

# ── Board config ──
echo ""
echo -e "${YELLOW}Project mapping${NC}"
read -rp "  Jira project key (e.g. PROJ): " JIRA_PROJECT
read -rp "  GitHub repo (e.g. org/repo): " GITHUB_REPO
read -rp "  Default branch [main]: " DEFAULT_BRANCH
DEFAULT_BRANCH=${DEFAULT_BRANCH:-main}

BOARDS_CONFIG="[{\"jiraProject\":\"$JIRA_PROJECT\",\"githubRepo\":\"$GITHUB_REPO\",\"defaultBranch\":\"$DEFAULT_BRANCH\",\"targetStatus\":\"Ready for Review\",\"escalationStatus\":\"Needs Clarity\"}]"

# ── Slack (optional) ──
echo ""
read -rp "Set up Slack? [y/N]: " SETUP_SLACK
SLACK_BOT_TOKEN=""
SLACK_SIGNING_SECRET=""

if [[ "$SETUP_SLACK" =~ ^[Yy] ]]; then
  echo ""
  echo "  Create a Slack app at: https://api.slack.com/apps"
  echo "  Add scopes: chat:write, im:history, app_mentions:read"
  echo "  Install to workspace, then copy the tokens below."
  read -rsp "  Bot token (xoxb-...): " SLACK_BOT_TOKEN
  echo ""
  read -rsp "  Signing secret: " SLACK_SIGNING_SECRET
  echo ""
fi

# ── Write .env ──
echo ""
echo -n "Writing .env... "

{
  echo "# Generated by scripts/setup.sh"
  echo ""
  echo "# Jira"
  echo "JIRA_HOST=$JIRA_HOST"
  echo "JIRA_AGENT_EMAIL=$JIRA_AGENT_EMAIL"
  echo "JIRA_API_TOKEN=$JIRA_API_TOKEN"
  echo "JIRA_AGENT_ACCOUNT_ID=$JIRA_ACCOUNT_ID"
  echo "JIRA_WEBHOOK_SECRET=$JIRA_WEBHOOK_SECRET"
  echo ""
  echo "# GitHub"
  if [ -n "$GITHUB_PAT" ]; then
    echo "GITHUB_PAT=$GITHUB_PAT"
  else
    echo "GITHUB_APP_ID=$GITHUB_APP_ID"
    echo "GITHUB_APP_PRIVATE_KEY=$GITHUB_APP_PRIVATE_KEY"
    echo "GITHUB_APP_INSTALLATION_ID=$GITHUB_APP_INSTALLATION_ID"
  fi
  echo ""
  echo "# Anthropic"
  echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
  echo ""
  echo "# Redis (Docker Compose overrides this)"
  echo "REDIS_URL=redis://localhost:6379"
  echo ""
  echo "# Board mapping"
  echo "BOARDS_CONFIG=$BOARDS_CONFIG"
  if [ -n "$SLACK_BOT_TOKEN" ]; then
    echo ""
    echo "# Slack"
    echo "SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN"
    echo "SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET"
  fi
} > .env

echo -e "${GREEN}done${NC}"

echo ""
echo -e "${GREEN}Setup complete.${NC}"
echo ""
echo "Next steps:"
echo "  ./scripts/start-local.sh    Start the agent + ngrok + register Jira webhook"
echo ""
